services:
    postgres:
        image: postgres
        shm_size: "8gb"
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - instacart_network
        volumes: 
            - instacart_postgres_data:/var/lib/postgresql
            - ./backup:/backup
    jupyter:
        build:
            context: .
            dockerfile: dockerfile.jupyter
        image: instacart_jupyter
        env_file:
            - .env
        ports:
            - "8888:8888"
        networks:
            - instacart_network
        volumes:
            - ./notebooks:/home/jovyan/work
    dbt:
        build:
            context: .
            dockerfile: dockerfile.dbt
        image: instacart_dbt
        env_file:
            - .env
        networks:
            - instacart_network
        working_dir: /app/dbt
        volumes: 
            - ./dbt:/app/dbt
            - ./dbt_profiles:/root/.dbt
        depends_on:
            - postgres
volumes:
    instacart_postgres_data:
        external: true
networks:
    instacart_network:
        external: true
