services:
    postgres:
        image: postgres
        shm_size: "8gb"
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - instacart_network
        volumes: 
            - instacart_postgres_data:/var/lib/postgresql
            - ./data/raw/:/data/:ro
            - ./sql/:/sql/:ro
            - ./backup:/backup
        command:
            - postgres
            - -c
            - max_wal_size=8GB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s
    data_ingest:
        env_file:
            - .env
        build:
            context: .
            dockerfile: scripts/dockerfile.raw_ingestion
        networks:
            - instacart_network
        volumes:
            - ./sql/:/sql/
        depends_on:
            postgres:
                condition: service_healthy
    jupyter:
        depends_on:
            dbt:
                condition: service_completed_successfully
        build:
            context: .
            dockerfile: dockerfile.jupyter
        image: instacart_jupyter
        env_file:
            - .env
        ports:
            - "8888:8888"
        networks:
            - instacart_network
        volumes:
            - ./notebooks:/home/jovyan/work
    dbt:
        depends_on:
            data_ingest:
                condition: service_completed_successfully
        build:
            context: .
            dockerfile: dockerfile.dbt
        image: instacart_dbt
        env_file:
            - .env
        networks:
            - instacart_network
        working_dir: /app/dbt
        volumes: 
            - ./dbt:/app/dbt
            - ./dbt_profiles:/root/.dbt
        command:
            - dbt
            - build
            - --project-dir
            - "/app/dbt/instacart"
            - --target
            - dev
volumes:
    instacart_postgres_data:
networks:
    instacart_network:
        driver: bridge
