FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-postgres \
    psycopg2-binary

COPY ./scripts/run_dbt.py /scripts/run_dbt.py

CMD ["python", "/scripts/run_dbt.py"]
